// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-layouts/MilestoneStrip.tsx": () => import("../components/mockups/landing-layouts/MilestoneStrip.tsx"),
  "./components/mockups/landing-layouts/ProgressiveHierarchy.tsx": () => import("../components/mockups/landing-layouts/ProgressiveHierarchy.tsx"),
  "./components/mockups/landing-layouts/SingleSource.tsx": () => import("../components/mockups/landing-layouts/SingleSource.tsx")
};
